version: '3.2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345678
    volumes:
      - type: volume
        source: db-data
        target: /db

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8010:8080
  
  taxiii-backend:
    build: ./Taxiii
    ports:
      - 8020:8080
volumes:
  db-data: