version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345678
    volumes:
      -db_data:/db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8010:8080
  
  taxiii-backend:
    build: ./Taxiii
    ports:
      -8020:8080
