version: '3.1'

services:
  taxiii-backend:
    container_name: taxiii-backend
    build: ./Taxiii
    ports:
      - 8081:8081
    # depends_on:
    #   - db
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/taxiii
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=taxiii
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
